services:
  postgres:
    image: postgres:17

    container_name: alveryn-postgres

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - alveryn-postgres-data:/var/lib/postgresql/data

    networks:
      - alveryn-network

volumes:
  alveryn-postgres-data:
    name: alveryn-postgres-data

networks:
  alveryn-network:
    name: alveryn-network
