services:
  - type: web
    name: alveryn-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: 10000
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        fromDatabase:
          name: alveryn-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: alveryn-db
          property: password

databases:
  - name: alveryn-db
    databaseName: alveryn
    user: alveryn
