package com.roomly.api.statistics.dto;

public enum InsightType {
  HOURS_CHANGE,
  GROSS_CHANGE,
  WORKED_DAYS_CHANGE,
  AVERAGE_SHIFT_CHANGE,
  BEST_WEEKDAY,
  MOST_USED_WORK_TYPE,
  STREAK,
  FORECAST_ABOVE_PREVIOUS_PERIOD,
  FORECAST_BELOW_PREVIOUS_PERIOD
}
