package com.roomly.api.statistics.model;

public enum StatisticsErrorCode {
  STATISTICS_INVALID_DATE_RANGE,
  STATISTICS_INVALID_COMPARISON_RANGE,
  STATISTICS_INCOMPATIBLE_COMPARISON,
  STATISTICS_HEATMAP_RANGE_TOO_LARGE,
  STATISTICS_GROSS_REQUIRES_CURRENCY_SELECTION,
  STATISTICS_UNSUPPORTED_HEATMAP_METRIC,
  STATISTICS_INVALID_HEATMAP_CURRENCY
}
