import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Mail, Pencil, Plus, UserCheck, UserMinus, UsersRound } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { useParams } from "react-router-dom";
import { createOrganizationMember, getTeamMemberHours, listOrganizationMembers, reactivateOrganizationMember, resendBusinessInvitation, suspendOrganizationMember, updateOrganizationMember } from "../api/endpoints";
import { getApiError } from "../api/api-errors";
import { BusinessManagementShell } from "../components/business-planning/business-management-shell";
import { Input } from "../components/ui/input";
import type { TeamMemberHours } from "../types/business";

type Period = "week" | "month";

export function BusinessPeoplePage() {
  const { organizationId = "" } = useParams(); const { t, i18n } = useTranslation("business"); const queryClient = useQueryClient();
  const [selectedId, setSelectedId] = useState<string | null>(null), [firstName, setFirstName] = useState(""), [lastName, setLastName] = useState(""), [email, setEmail] = useState(""), [error, setError] = useState(""), [period, setPeriod] = useState<Period>("month");
  const members = useQuery({ queryKey: ["organizations", organizationId, "members"], queryFn: () => listOrganizationMembers(organizationId) });
  const selected = members.data?.find((member) => member.id === selectedId) ?? null;
  const range = useMemo(() => rangeFor(period), [period]);
  const hours = useQuery({ queryKey: ["organizations", organizationId, "members", selectedId, "hours", range.from, range.to], queryFn: () => getTeamMemberHours(organizationId, selectedId!, range.from, range.to), enabled: Boolean(selectedId), retry: false });
  useEffect(() => { if (!selected) return; setFirstName(selected.firstName ?? ""); setLastName(selected.lastName ?? ""); setEmail(selected.email ?? ""); }, [selected]);
  const refresh = () => queryClient.invalidateQueries({ queryKey: ["organizations", organizationId, "members"] });
  const save = useMutation({ mutationFn: () => selected ? updateOrganizationMember(organizationId, selected.id, { firstName: firstName.trim(), lastName: lastName.trim(), email: email.trim() || null }) : createOrganizationMember(organizationId, { firstName: firstName.trim(), lastName: lastName.trim(), email: email.trim() || null, language: i18n.language }), onSuccess: async (value) => { setSelectedId(value.id); setError(""); await refresh(); }, onError: (cause) => setError(getApiError(cause).message) });
  const status = useMutation({ mutationFn: () => selected!.status === "SUSPENDED" ? reactivateOrganizationMember(organizationId, selected!.id) : suspendOrganizationMember(organizationId, selected!.id), onSuccess: refresh, onError: (cause) => setError(getApiError(cause).message) });
  const resend = useMutation({ mutationFn: () => resendBusinessInvitation(organizationId, selected!.id, i18n.language), onError: (cause) => setError(getApiError(cause).message) });
  const beginCreate = () => { setSelectedId(null); setFirstName(""); setLastName(""); setEmail(""); };
  return <BusinessManagementShell><div className="business-admin">
    <header className="business-admin__header"><div><p>{t("management.people.eyebrow")}</p><h1>{t("members.title")}</h1><span>{t("management.people.description")}</span></div><button type="button" onClick={beginCreate}><Plus />{t("members.add")}</button></header>
    <div className="business-admin__layout"><section className="business-admin__panel"><div className="business-admin__panel-title"><UsersRound /><div><h2>{t("members.title")}</h2><p>{t("management.people.count", { count: (members.data ?? []).length })}</p></div></div><div className="business-admin__list">{(members.data ?? []).map((member) => { const name = [member.firstName, member.lastName].filter(Boolean).join(" ") || member.email || t("members.noEmail"); const accessState = member.accessState ?? (member.userId ? "CLAIMED" : member.email ? "INVITED" : "MANAGED"); return <button key={member.id} type="button" className={`business-admin__row business-admin__row-button ${selectedId === member.id ? "is-selected" : ""}`} onClick={() => setSelectedId(member.id)}><span className="business-admin__avatar">{name.slice(0, 2).toUpperCase()}</span><span><strong>{name}</strong><small>{member.email || t("members.noEmail")}</small></span><span className={`business-admin__status is-${member.status.toLowerCase()}`}>{member.status === "SUSPENDED" ? t(`memberStatus.${member.status}`) : accessState === "MANAGED" ? "Managed employee" : accessState === "INVITED" ? "Invitation pending" : "Active account"}</span><Pencil className="business-admin__edit-icon" /></button>; })}</div></section>
      <aside className="business-admin__panel business-admin__form"><div><p>{t(selected ? "management.people.edit" : "management.people.new")}</p><h2>{selected ? [selected.firstName, selected.lastName].filter(Boolean).join(" ") : t("members.add")}</h2></div><Input label={t("members.firstName")} value={firstName} onChange={(event) => setFirstName(event.target.value)} /><Input label={t("members.lastName")} value={lastName} onChange={(event) => setLastName(event.target.value)} /><Input label={t("members.email")} type="email" value={email} disabled={Boolean(selected?.userId)} onChange={(event) => setEmail(event.target.value)} /><button className="business-admin__primary" disabled={(!firstName.trim() && !lastName.trim()) || save.isPending} onClick={() => save.mutate()}>{selected ? t("save") : t("members.action")}</button>{selected && (selected.accessState ?? (selected.userId ? "CLAIMED" : selected.email ? "INVITED" : "MANAGED")) === "INVITED" && selected.email ? <button className="business-admin__secondary" disabled={resend.isPending} onClick={() => resend.mutate()}><Mail />{t("management.people.resend")}</button> : null}{selected ? <button className="business-admin__secondary" disabled={status.isPending} onClick={() => status.mutate()}>{selected.status === "SUSPENDED" ? <UserCheck /> : <UserMinus />}{selected.status === "SUSPENDED" ? t("members.reactivate") : t("members.suspend")}</button> : null}{selected ? <TeamHours hours={hours.data} loading={hours.isLoading} error={hours.error ? getApiError(hours.error).message : ""} period={period} onPeriod={setPeriod} /> : null}</aside>
    </div>{error ? <p className="business-admin__error" role="alert">{error}</p> : null}
  </div></BusinessManagementShell>;
}

export function TeamHours({hours,loading,error,period,onPeriod}:{hours:TeamMemberHours|undefined;loading:boolean;error:string;period:Period;onPeriod:(value:Period)=>void}){return <section aria-label="Team hours" className="mt-5 border-t border-white/10 pt-4 text-sm text-white/70"><h3 className="font-semibold text-white">Employee history · server-calculated</h3><button type="button" aria-pressed={period==="week"} onClick={()=>onPeriod("week")}>Week</button> <button type="button" aria-pressed={period==="month"} onClick={()=>onPeriod("month")}>Month</button>{loading?<p>Loading time summary…</p>:null}{error?<p role="alert">{error}</p>:null}{!loading&&!error&&!hours?<p>No time data is available.</p>:null}{hours?<><p>{hours.daysWorked} days worked · planned {formatMinutes(hours.plannedMinutes)} · worked {formatMinutes(hours.workedMinutes)}</p>{hours.days.length?hours.days.map(day=><div key={day.date}><strong>{day.date}</strong> {formatMinutes(day.plannedMinutes)} planned / {formatMinutes(day.workedMinutes)} worked {day.openSessions?`${day.openSessions} open `:""}{day.incompleteSessions?`${day.incompleteSessions} incomplete `:""}{day.correctedSessions?`${day.correctedSessions} corrected`:""}</div>):<p>No time data is available.</p>}<p>Weekly: {hours.weeks.map(value=>`${value.startDate} ${formatMinutes(value.workedMinutes)}`).join(" · ")||"—"}</p><p>Monthly: {hours.months.map(value=>`${value.startDate} ${formatMinutes(value.workedMinutes)}`).join(" · ")||"—"}</p>{hours.sessions?.length?<div aria-label="Work session history">{hours.sessions.map((session,index)=><div key={`${session.date}-${index}`}><strong>{session.date}</strong> · {session.unitName} · {session.workTypeName} · {session.actualStartTime??session.plannedStartTime??"—"}–{session.actualEndTime??session.plannedEndTime??"—"} · break {formatMinutes(session.breakMinutes)} · {session.netMinutes==null?session.state.toLowerCase():formatMinutes(session.netMinutes)}</div>)}</div>:null}</>:null}</section>}
function rangeFor(period:Period){const now=new Date();const today=localDate(now);if(period==="month")return {from:`${today.slice(0,8)}01`,to:today};const monday=new Date(now);monday.setDate(now.getDate()-((now.getDay()+6)%7));return {from:localDate(monday),to:today};}
function localDate(value:Date){return `${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`;}
function formatMinutes(minutes:number){return `${Math.floor(minutes/60)}h ${minutes%60}m`;}
