import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Pencil, Plus, ShieldCheck, Trash2, X } from "lucide-react";
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { useParams } from "react-router-dom";
import { assignOrganizationRole, createOrganizationRole, deleteOrganizationRole, listOrganizationMembers, listOrganizationRoleAssignments, listOrganizationRoles, listOrganizationUnits, removeOrganizationRoleAssignment, updateOrganizationRole } from "../api/endpoints";
import { getApiError } from "../api/api-errors";
import { BusinessManagementShell } from "../components/business-planning/business-management-shell";
import { Input } from "../components/ui/input";
import { Select } from "../components/ui/select";
import type { OrganizationPermission } from "../types/business";

const permissions: OrganizationPermission[] = ["VIEW_SCHEDULE", "MANAGE_SCHEDULE", "PUBLISH_SCHEDULE", "VIEW_TEAM_HOURS", "APPROVE_ACTUALS", "MANAGE_ABSENCES", "MANAGE_MEMBERS", "MANAGE_TEAMS", "MANAGE_ROLES", "MANAGE_SETTINGS"];
export function BusinessRolesPage() {
  const { organizationId = "" } = useParams(); const { t } = useTranslation("business"); const queryClient = useQueryClient();
  const [selectedRoleId, setSelectedRoleId] = useState<string | null>(null), [name, setName] = useState(""), [selectedPermissions, setSelectedPermissions] = useState<OrganizationPermission[]>([]), [memberId, setMemberId] = useState(""), [roleId, setRoleId] = useState(""), [unitId, setUnitId] = useState(""), [includeChildren, setIncludeChildren] = useState(true), [error, setError] = useState("");
  const roles = useQuery({ queryKey: ["organizations", organizationId, "roles"], queryFn: () => listOrganizationRoles(organizationId) });
  const members = useQuery({ queryKey: ["organizations", organizationId, "members"], queryFn: () => listOrganizationMembers(organizationId) });
  const units = useQuery({ queryKey: ["organizations", organizationId, "units"], queryFn: () => listOrganizationUnits(organizationId) });
  const assignments = useQuery({ queryKey: ["organizations", organizationId, "role-assignments"], queryFn: () => listOrganizationRoleAssignments(organizationId) });
  const selectedRole = roles.data?.find((role) => role.id === selectedRoleId) ?? null;
  useEffect(() => { if (!selectedRole) return; setName(selectedRole.name); setSelectedPermissions(selectedRole.permissions); }, [selectedRole]);
  const refreshRoles = () => queryClient.invalidateQueries({ queryKey: ["organizations", organizationId, "roles"] });
  const refreshAssignments = () => queryClient.invalidateQueries({ queryKey: ["organizations", organizationId, "role-assignments"] });
  const save = useMutation({ mutationFn: () => selectedRole ? updateOrganizationRole(organizationId, selectedRole.id, { name: name.trim(), permissions: selectedPermissions }) : createOrganizationRole(organizationId, { name: name.trim(), permissions: selectedPermissions }), onSuccess: async (value) => { setSelectedRoleId(value.id); setError(""); await refreshRoles(); }, onError: (cause) => setError(getApiError(cause).message) });
  const removeRole = useMutation({ mutationFn: () => deleteOrganizationRole(organizationId, selectedRole!.id), onSuccess: async () => { setSelectedRoleId(null); setName(""); setSelectedPermissions([]); await Promise.all([refreshRoles(), refreshAssignments()]); }, onError: (cause) => setError(getApiError(cause).message) });
  const assign = useMutation({ mutationFn: () => assignOrganizationRole(organizationId, { membershipId: memberId, roleId, unitId: unitId || null, includeDescendants: includeChildren }), onSuccess: refreshAssignments, onError: (cause) => setError(getApiError(cause).message) });
  const unassign = useMutation({ mutationFn: (id: string) => removeOrganizationRoleAssignment(organizationId, id), onSuccess: refreshAssignments, onError: (cause) => setError(getApiError(cause).message) });
  const personName = (id: string) => { const member = members.data?.find((value) => value.id === id); return [member?.firstName, member?.lastName].filter(Boolean).join(" ") || member?.email || "—"; };
  const beginCreate = () => { setSelectedRoleId(null); setName(""); setSelectedPermissions([]); };
  return <BusinessManagementShell><div className="business-admin">
    <header className="business-admin__header"><div><p>{t("management.roles.eyebrow")}</p><h1>{t("tabs.roles")}</h1><span>{t("management.roles.description")}</span></div><button onClick={beginCreate}><Plus />{t("roles.create")}</button></header>
    <div className="business-admin__roles"><section className="business-admin__panel"><div className="business-admin__panel-title"><ShieldCheck /><div><h2>{t("tabs.roles")}</h2><p>{t("management.roles.count", { count: (roles.data ?? []).length })}</p></div></div><div className="business-admin__list">{(roles.data ?? []).map((role) => <button type="button" key={role.id} className={`business-admin__role business-admin__role-button ${selectedRoleId === role.id ? "is-selected" : ""}`} onClick={() => setSelectedRoleId(role.id)}><div><strong>{role.name}</strong>{role.systemRole ? <span>{t("management.roles.system")}</span> : null}<Pencil /></div><p>{role.permissions.map((value) => t(`permissions.${value}`)).join(" · ")}</p></button>)}</div></section>
      <aside className="business-admin__panel business-admin__form"><div><p>{t(selectedRole ? "management.roles.edit" : "management.roles.new")}</p><h2>{selectedRole?.name ?? t("roles.create")}</h2></div><Input label={t("roles.name")} value={name} disabled={selectedRole?.systemRole} onChange={(event) => setName(event.target.value)} /><div className="business-admin__permissions">{permissions.map((permission) => <label key={permission}><input type="checkbox" disabled={selectedRole?.systemRole} checked={selectedPermissions.includes(permission)} onChange={() => setSelectedPermissions((current) => current.includes(permission) ? current.filter((value) => value !== permission) : [...current, permission])} /><span>{t(`permissions.${permission}`)}</span></label>)}</div><button className="business-admin__primary" disabled={selectedRole?.systemRole || !name.trim() || !selectedPermissions.length || save.isPending} onClick={() => save.mutate()}>{selectedRole ? t("save") : t("roles.createAction")}</button>{selectedRole && !selectedRole.systemRole ? <button className="business-admin__danger" disabled={removeRole.isPending} onClick={() => removeRole.mutate()}><Trash2 />{t("management.roles.delete")}</button> : null}</aside>
      <section className="business-admin__panel business-admin__assignment"><div><p>{t("management.roles.assignEyebrow")}</p><h2>{t("roles.assign")}</h2></div><div className="business-admin__assign-grid"><Select label={t("roles.person")} value={memberId} onChange={(event) => setMemberId(event.target.value)}><option value="">{t("planner.select")}</option>{(members.data ?? []).map((member) => <option key={member.id} value={member.id}>{personName(member.id)}</option>)}</Select><Select label={t("roles.role")} value={roleId} onChange={(event) => setRoleId(event.target.value)}><option value="">{t("planner.select")}</option>{(roles.data ?? []).map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</Select><Select label={t("roles.scope")} value={unitId} onChange={(event) => setUnitId(event.target.value)}><option value="">{t("roles.wholeOrganization")}</option>{(units.data ?? []).map((unit) => <option key={unit.id} value={unit.id}>{unit.name}</option>)}</Select></div><label className="business-admin__check"><input type="checkbox" checked={includeChildren} onChange={(event) => setIncludeChildren(event.target.checked)} />{t("roles.includeDescendants")}</label><button className="business-admin__primary" disabled={!memberId || !roleId || assign.isPending} onClick={() => assign.mutate()}>{t("roles.assignAction")}</button><div className="business-admin__chips">{(assignments.data ?? []).map((assignment) => <span key={assignment.id}><strong>{personName(assignment.membershipId)}</strong> · {roles.data?.find((role) => role.id === assignment.roleId)?.name} · {units.data?.find((unit) => unit.id === assignment.unitId)?.name || t("roles.wholeOrganization")}<button aria-label={t("management.roles.removeAssignment")} onClick={() => unassign.mutate(assignment.id)}><X /></button></span>)}</div></section>
    </div>{error ? <p className="business-admin__error" role="alert">{error}</p> : null}
  </div></BusinessManagementShell>;
}
