import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { ChevronLeft,ChevronRight,LogIn,LogOut } from "lucide-react";
import { useMemo,useState } from "react";
import { useTranslation } from "react-i18next";
import { checkInBusinessAssignment,checkOutBusinessAssignment,createMyBusinessAbsenceRequest,getPersonalBusinessSchedule,listMyBusinessAbsenceRequests } from "../api/endpoints";
import { Card } from "../components/ui/card";

export function SchedulePage(){
 const {t,i18n}=useTranslation("business");const client=useQueryClient();const [weekStart,setWeekStart]=useState(()=>monday(new Date()));const days=useMemo(()=>Array.from({length:7},(_,i)=>addDays(weekStart,i)),[weekStart]);const from=iso(days[0]),to=iso(days[6]);
 const schedule=useQuery({queryKey:["personal-business-schedule",from],queryFn:()=>getPersonalBusinessSchedule(from,to)});const requests=useQuery({queryKey:["business-absence-requests","my"],queryFn:listMyBusinessAbsenceRequests});const [requestOpen,setRequestOpen]=useState(false);
 const requestAbsence=useMutation({mutationFn:(form:HTMLFormElement)=>{const data=new FormData(form);return createMyBusinessAbsenceRequest({organizationId:String(data.get("organizationId")),type:String(data.get("type")) as "REST_DAY"|"VACATION"|"SICK",startDate:String(data.get("startDate")),endDate:String(data.get("endDate")),notes:String(data.get("notes")||"")||null});},onSuccess:async()=>{setRequestOpen(false);await client.invalidateQueries({queryKey:["business-absence-requests"]});}});
 const checkIn=useMutation({mutationFn:checkInBusinessAssignment,onSuccess:async()=>{await client.invalidateQueries({queryKey:["personal-business-schedule"]});}});const checkOut=useMutation({mutationFn:checkOutBusinessAssignment,onSuccess:async()=>{await client.invalidateQueries({queryKey:["personal-business-schedule"]});}});
 return <div className="space-y-5 pb-28"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-300/70">Alveryn Business</p><h1 className="text-2xl font-bold text-white">{t("schedule.title")}</h1></div>
 <Card className="p-4"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-white">{t("schedule.myRequests")}</h2><p className="text-xs text-white/40">{t("schedule.pendingCount",{count:requests.data?.filter(value=>value.status==="PENDING").length??0})}</p></div><button onClick={()=>setRequestOpen(value=>!value)} className="rounded-xl bg-emerald-400 px-4 py-2 text-sm font-bold text-emerald-950">{t("schedule.requestAbsence")}</button></div>{requestOpen&&<form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={event=>{event.preventDefault();requestAbsence.mutate(event.currentTarget);}}><select required name="organizationId" aria-label={t("organization")} className="rounded-xl bg-white/10 p-3 text-white"><option value="">{t("organization")}</option>{(schedule.data??[]).map(org=><option key={org.organizationId} value={org.organizationId}>{org.organizationName}</option>)}</select><select name="type" aria-label={t("schedule.absenceType")} className="rounded-xl bg-white/10 p-3 text-white"><option value="VACATION">{t("dayTypes.VACATION")}</option><option value="SICK">{t("dayTypes.SICK")}</option><option value="REST_DAY">{t("dayTypes.REST_DAY")}</option></select><input aria-label={t("schedule.startDate")} required name="startDate" type="date" defaultValue={from} className="rounded-xl bg-white/10 p-3 text-white"/><input aria-label={t("schedule.endDate")} required name="endDate" type="date" defaultValue={from} className="rounded-xl bg-white/10 p-3 text-white"/><textarea name="notes" aria-label={t("schedule.notes")} placeholder={t("schedule.notes")} className="min-h-20 rounded-xl bg-white/10 p-3 text-white sm:col-span-2"/><button className="rounded-xl bg-emerald-400 p-3 font-bold text-emerald-950 sm:col-span-2">{t("schedule.sendManager")}</button></form>}{!!requests.data?.length&&<div className="mt-3 flex gap-2 overflow-x-auto">{requests.data.slice(0,6).map(value=><div key={value.id} className="min-w-44 rounded-xl bg-white/[0.04] p-3 text-xs"><strong className="text-white">{t(`dayTypes.${value.type}`)} · {t(`schedule.status.${value.status}`)}</strong><p className="mt-1 text-white/40">{value.startDate} — {value.endDate}</p></div>)}</div>}</Card>
 <div className="flex items-center justify-between"><button aria-label={t("schedule.previousWeek")} onClick={()=>setWeekStart(addDays(weekStart,-7))} className="rounded-xl bg-white/5 p-2 text-white"><ChevronLeft/></button><strong className="text-white">{from} — {to}</strong><button aria-label={t("schedule.nextWeek")} onClick={()=>setWeekStart(addDays(weekStart,7))} className="rounded-xl bg-white/5 p-2 text-white"><ChevronRight/></button></div>{schedule.isLoading&&<p className="text-white/45">{t("loading")}</p>}
 {(schedule.data??[]).map(org=><Card key={org.organizationId} className="overflow-hidden p-0"><div className="border-b border-white/10 p-4"><h2 className="font-semibold text-white">{org.organizationName}</h2><p className="text-xs text-white/40">{t("schedule.highlighted")}</p></div><div className="overflow-x-auto"><div className="grid min-w-[840px] grid-cols-7">{days.map(day=>{const date=iso(day),assignments=org.assignments.filter(item=>item.date===date);return <div key={date} className="min-h-48 border-r border-white/[0.08] p-2 last:border-0"><p className="mb-2 text-center text-xs font-semibold text-white/45">{day.toLocaleDateString(i18n.resolvedLanguage,{weekday:"short",day:"2-digit"})}</p>{assignments.map(assignment=>{const canCheck=assignment.checkInMode!=="DISABLED",started=Boolean(assignment.result?.checkedInAt),finished=Boolean(assignment.result?.checkedOutAt);return <div key={assignment.id} className="mb-2 rounded-xl border border-emerald-400/50 bg-emerald-400/12 p-2" style={{borderLeftColor:assignment.color,borderLeftWidth:4}}><strong className="block text-xs text-white">{assignment.workTypeCode} · {assignment.workTypeName}</strong><span className="text-[11px] text-white/45">{time(assignment.startTime,assignment.endTime)}</span>{canCheck&&!started&&<button disabled={checkIn.isPending} onClick={()=>checkIn.mutate(assignment.id)} className="mt-2 flex w-full items-center justify-center gap-1 rounded-lg bg-emerald-400 px-2 py-1.5 text-[11px] font-bold text-emerald-950"><LogIn className="h-3 w-3"/>{t("schedule.checkIn")}</button>}{canCheck&&started&&!finished&&<button disabled={checkOut.isPending} onClick={()=>checkOut.mutate(assignment.id)} className="mt-2 flex w-full items-center justify-center gap-1 rounded-lg bg-amber-300 px-2 py-1.5 text-[11px] font-bold text-amber-950"><LogOut className="h-3 w-3"/>{t("schedule.checkOut")}</button>}{finished&&<p className="mt-2 text-[10px] font-semibold text-emerald-300">{t("schedule.timeSubmitted")} · {time(assignment.result?.actualStartTime??null,assignment.result?.actualEndTime??null)}</p>}</div>})}{org.dayEntries.filter(entry=>entry.date===date).map(entry=><div key={entry.id} className="mb-2 rounded-xl bg-violet-400/10 p-2 text-xs font-semibold text-violet-200">{t(`dayTypes.${entry.type}`)}</div>)}</div>})}</div></div></Card>)}{!schedule.isLoading&&!schedule.data?.length&&<Card className="p-5 text-sm text-white/45">{t("schedule.empty")}</Card>}</div>;
}
function time(start:string|null,end:string|null){return start?`${start.slice(0,5)}${end?`–${end.slice(0,5)}`:""}`:"—"}function monday(value:Date){const d=new Date(value);d.setHours(12,0,0,0);const n=d.getDay()||7;d.setDate(d.getDate()-n+1);return d}function addDays(value:Date,n:number){const d=new Date(value);d.setDate(d.getDate()+n);return d}function iso(value:Date){return `${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`}
