package com.roomly.api.imports.model;

public enum ExcelImportErrorCode {
  EXCEL_FILE_REQUIRED,
  EXCEL_FILE_TOO_LARGE,
  EXCEL_INVALID_TYPE,
  EXCEL_CORRUPTED,
  EXCEL_ENCRYPTED,
  EXCEL_YEAR_MISSING,
  EXCEL_YEAR_CONFLICT,
  EXCEL_NO_SUPPORTED_SHEETS,
  EXCEL_NO_IMPORTABLE_ROWS,
  EXCEL_ALREADY_IMPORTED,
  EXCEL_PREVIEW_EXPIRED,
  EXCEL_PREVIEW_ALREADY_USED,
  EXCEL_IMPORT_CONFLICT,
  EXCEL_BATCH_NOT_FOUND,
  EXCEL_BATCH_ALREADY_UNDONE
}
